version: "3.8"

services:
  backend:
    build: ./ecommerce-backend
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/data
    networks:
      - app-network

  frontend:
    build: ./ecommerce-project
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  sqlite_data:

networks:
  app-network:
