version: "3.8"

services:
  backend:
    build: ./ecommerce-backend
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/data
    networks:
      - app-network

  frontend:
    build: ./ecommerce-project
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:3000

volumes:
  sqlite_data:

networks:
  app-network:
