version: "3.8"

services:
  backend:
    build:
      context: ./ecommerce-backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ecommerce-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./ecommerce-project
      dockerfile: dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
